set runtimepath+=/home/joel/.vim_runtime

source /home/joel/.vim_runtime/vimrcs/basic.vim
source /home/joel/.vim_runtime/vimrcs/filetypes.vim

try
source /home/joel/.vim_runtime/my_configs.vim
catch
endtry

" Inject Pathogen
execute pathogen#infect()
call pathogen#helptags()

" Config
set number
set mouse=a
set foldcolumn=2
"set cursorline
"set termguicolors

" Settup clipboard for +clipboard and +xterm_clipboard
if has('unnamedplus')
  set clipboard=unnamed,unnamedplus
endif

set autoread
let javascript_fold=0 "desactive js fold
set foldlevelstart=20

" Remove vertical |
set fillchars+=vert:\  " witespace

" Customize NerdTree config
map <C-n> :NERDTreeToggle<CR>

" Set color theme
let g:nord_italic = 1
let g:nord_underline = 1
let g:nord_italic_comments = 1
let g:nord_uniform_status_lines = 1
"let g:nord_cursor_line_number_background = 1
"let g:nord_comment_brightness = 16

colorscheme nord

set guifont=Monaco:h10 noanti

" Goyo custom config
let g:goyo_width = 120

function! s:goyo_enter()
  let b:quitting = 0
  let b:quitting_bang = 0
  autocmd QuitPre <buffer> let b:quitting = 1
  cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!

  "setlocal wrap linebreak nolist
  set virtualedit=
  setlocal display+=lastline
  noremap  <buffer> <silent> k gk
  noremap  <buffer> <silent> j gj
  noremap  <buffer> <silent> 0 g0
  noremap  <buffer> <silent> $ g$
  noremap  <buffer> <silent> <Up>   gk
  noremap  <buffer> <silent> <Down> gj
  noremap  <buffer> <silent> <Home> g<Home>
  noremap  <buffer> <silent> <End>  g<End>
  inoremap <buffer> <silent> <Up>   <C-o>gk
  inoremap <buffer> <silent> <Down> <C-o>gj
  inoremap <buffer> <silent> <Home> <C-o>g<Home>
  inoremap <buffer> <silent> <End>  <C-o>g<End>
endfunction

function! s:goyo_leave()
  " Quit Vim if this is the only remaining buffer
  if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
    if b:quitting_bang
      qa!
    else
      qa
    endif
  endif

  set virtualedit=all
  silent! nunmap <buffer> k
  silent! nunmap <buffer> j
  silent! nunmap <buffer> 0
  silent! nunmap <buffer> $
  silent! nunmap <buffer> <Up>
  silent! nunmap <buffer> <Down>
  silent! nunmap <buffer> <Home>
  silent! nunmap <buffer> <End>
  silent! iunmap <buffer> <Up>
  silent! iunmap <buffer> <Down>
  silent! iunmap <buffer> <Home>
  silent! iunmap <buffer> <End>
endfunction

" Trigger costum config on Goyo enter/leave
autocmd! User GoyoEnter call <SID>goyo_enter()
autocmd! User GoyoLeave call <SID>goyo_leave()

